/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ghc72ctaz5bopks4gspx4kx5yy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-crefptvzwbgupgi44ez5gshdla",
    "aws_cognito_identity_pool_id": "us-east-1:5c53ef18-3ffb-4817-bd27-c3ab99880762",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bDSaUD278",
    "aws_user_pools_web_client_id": "7v9cpn86q3g1gpm4aqps7vp9lv",
    "oauth": {}
};


export default awsmobile;
